version: "3.7"

services:
  c-lang:
    build:
      context: .
      target: c-lang
    image: multi-lang-battle-c-lang
    command: 'make build_run'
    volumes:
      - ./apps/c-lang:/apps/c-lang
  
  cpp:
    build:
      context: .
      target: cpp
    image: multi-lang-ba_ttle-cpp
    command: 'make build_run'
    volumes:
      - ./apps/cpp:/apps/cpp
