version: "3.7"

services:
  c-lang:
    build:
      context: .
      target: c-lang
    image: multi-lang-battle-c-lang
    command: "make build_run"
    volumes:
      - ./apps/c-lang:/apps/c-lang
      - ./fixtures/:/fixtures

  cpp:
    build:
      context: .
      target: cpp
    image: multi-lang-battle-cpp
    command: "make build_run"
    volumes:
      - ./apps/cpp:/apps/cpp
      - ./fixtures/:/fixtures

  go:
    build:
      context: .
      target: go
    image: multi-lang-battle-go
    command: "make build_run"
    volumes:
      - ./apps/go:/apps/go
      - ./fixtures/:/fixtures

  java:
    build:
      context: .
      target: java
    image: multi-lang-battle-java
    command: "make build_run"
    volumes:
      - ./apps/java:/apps/java
      - ./fixtures/:/fixtures
